#!/bin/sh

set -eu

_usage() {
  cat >&2 <<EOF
usage:
  myfreebsd bwdev
  myfreebsd bk
  myfreebsd bkdev
  myfreebsd ci
  myfreebsd dirdeps
EOF
  exit 64 # EX_USAGE
}

buildworld_dev() {
  # NOTE rebuilding world without ccache takes a while, so uncomment this only if you need it.
  #make -C "${src}" ${_make_args} cleanworld
  make -C "${src}" -j"${parallelism}" ${_make_args} buildworld
}

buildkernel_parallel() {
  make -C "${src}" ${_make_args} KERNCONF=SIVAKERN cleankernel
  make -C "${src}" -j"${parallelism}" -k ${_make_args} KERNCONF=SIVAKERN buildkernel
}

buildkernel_dev_single() {
  make -C "${src}" -j1 ${_make_args} KERNCONF=SIVAKERN buildkernel
}

dirdeps_build() {
  make -C "${src}" -j"${parallelism}" \
    __MAKE_CONF=${top}/dev/make.conf \
    SRCCONF=${top}/dev/src.conf \
    SRC_ENV_CONF=${top}/dev/dirdeps_src-env.conf \
    WITH_DIRDEPS_BUILD= \
    the-lot
}

_ci() {
  doas make -C "${src}/tests/ci" ${_make_args} "$@" clean || true
  doas make -C "${src}/tests/ci" ${_make_args} "$@" ci
  #make -C "${src}/tests/ci" ${_make_args} \
  #  -DNO_ROOT \
  #  TIMEOUT_MS="16200000" \
  #  "$@" \
  #  ci
}

_ci_parallel() {
  _outdir="$(doas mktemp -d /tmp/siva.XXXXXX)"
  doas chmod 0755 "${_outdir}"
  doas mkdir -p "${_outdir}/ci1" "${_outdir}/ci2"

  doas make -C "${src}/tests/ci" ${_make_args} clean || true
  doas make -C "${src}/tests/ci" ${_make_args} CITYPE=full CIDISK="${_outdir}/ci1/disk.raw" ci-buildimage
  doas cp "${_outdir}/ci1/disk.raw" "${_outdir}/ci2/disk.raw"

  tmux -f /dev/null \
  	new-session -d -s myfreebsdci -n runs "doas ./porch-ci.sh ${_outdir}/ci1 'sys' 2>&1 | tee ${_outdir}/ci1/run.log" \; \
  	split-window -h -t myfreebsdci:runs   "doas ./porch-ci.sh ${_outdir}/ci2 'bin sbin usr.bin usr.sbin etc share cddl include lib libexec' 2>&1 | tee ${_outdir}/ci2/run.log"
  env -u TMUX tmux -f /dev/null attach-session -t myfreebsdci > /dev/null
  echo "All output logs are in ${_outdir}"
}

realpath="$(realpath "$0")"
top="$(dirname "${realpath}")"
_make_args="__MAKE_CONF=${top}/dev/make.conf MAKECONF=${top}/dev/make.conf SRCCONF=${top}/dev/src.conf SRC_ENV_CONF=${top}/dev/src-env.conf"

while getopts j:s: name
do
  case "${name}" in
    j) parallelism="${OPTARG}" ;;
    s) src="${OPTARG}" ;;
    ?)
      echo "Usage: $0: [-j numjobs] command" >&2
      exit 64 # EX_USAGE
      ;;
    *) ;;
  esac
done
shift $((OPTIND - 1))
: "${parallelism:=$(nproc)}"
: "${src:=${HOME}/src/freebsd-src}"

cmd="$1"
shift

case "${cmd}" in
  bwdev) buildworld_dev ;;
  bk) buildkernel_parallel ;;
  bkdev) buildkernel_dev_single ;;
  dirdeps) dirdeps_build ;;
  ci) _ci "$@" ;;
  parci) _ci_parallel "$@" ;;
  *)
      echo "ERROR: unrecognized command '${cmd}'" >&2
      _usage
esac
