#!/bin/sh

set -eux

_usage() {
  cat >&2 <<EOF
usage:
  myfreebsd bktags
  myfreebsd bkdev
EOF
  exit 64 # EX_USAGE
}

# TODO doesn't work yet for some reason
buildkernel_tags() {
  make -C "${src}" __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" CTAGS=ctags tags
}

buildworld_dev() {
  # NOTE rebuilding world without ccache takes a while, so uncomment this only if you need it.
  #make -C "${src}" __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" cleanworld
  make -C "${src}" -j"${j}" __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" buildworld
}

buildkernel_parallel() {
  make -C "${src}" __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" KERNCONF=SIVAKERN cleankernel
  make -C "${src}" -j"${j}" -k __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" KERNCONF=SIVAKERN buildkernel
}

buildkernel_dev_single() {
  make -C "${src}" -j1 __MAKE_CONF="${top}/dev/make.conf" SRCCONF="${top}/dev/src.conf" SRC_ENV_CONF="${top}/dev/src-env.conf" KERNCONF=SIVAKERN buildkernel
}

realpath="$(realpath "$0")"
top="$(dirname "${realpath}")"
src="${HOME}/src/freebsd-src"
j="${J:-$(nproc)}"

case "$1" in
  bwdev) buildworld_dev ;;
  bk) buildkernel_parallel ;;
  bkdev) buildkernel_dev_single ;;
  bktags) buildkernel_tags ;;
  *)
      echo "ERROR: unrecognized command '$1'" >&2
      _usage
esac
