#!/bin/sh

set -eu

_usage() {
  cat >&2 <<EOF
usage:
  myfreebsd bwdev
  myfreebsd bk
  myfreebsd bkdev
  myfreebsd ci
  myfreebsd dirdeps
EOF
  exit 64 # EX_USAGE
}

buildworld_dev() {
  # NOTE rebuilding world without ccache takes a while, so uncomment this only if you need it.
  #make -C "${src}" ${_make_args} cleanworld
  make -C "${src}" -j"${parallelism}" ${_make_args} buildworld
}

buildkernel_parallel() {
  make -C "${src}" ${_make_args} KERNCONF=SIVAKERN cleankernel
  make -C "${src}" -j"${parallelism}" -k ${_make_args} KERNCONF=SIVAKERN buildkernel
}

buildkernel_dev_single() {
  make -C "${src}" -j1 ${_make_args} KERNCONF=SIVAKERN buildkernel
}

dirdeps_build() {
  make -C "${src}" -j"${parallelism}" \
    __MAKE_CONF=${top}/dev/make.conf \
    SRCCONF=${top}/dev/src.conf \
    SRC_ENV_CONF=${top}/dev/dirdeps_src-env.conf \
    WITH_DIRDEPS_BUILD= \
    the-lot
}

_ci() {
  doas make -C "${src}/tests/ci" ${_make_args} "$@" clean || true
  doas make -C "${src}/tests/ci" ${_make_args} "$@" ci
  #make -C "${src}/tests/ci" ${_make_args} \
  #  -DNO_ROOT \
  #  TIMEOUT_MS="16200000" \
  #  "$@" \
  #  ci
}

realpath="$(realpath "$0")"
top="$(dirname "${realpath}")"
src="${HOME}/src/freebsd-src"
_make_args="__MAKE_CONF=${top}/dev/make.conf MAKECONF=${top}/dev/make.conf SRCCONF=${top}/dev/src.conf SRC_ENV_CONF=${top}/dev/src-env.conf"

while getopts j: name
do
  case "${name}" in
    j) parallelism="${OPTARG}" ;;
    ?)
      echo "Usage: $0: [-j numjobs] command" >&2
      exit 64 # EX_USAGE
      ;;
    *) ;;
  esac
done
shift $((OPTIND - 1))
: "${parallelism:=$(nproc)}"

cmd="$1"
shift

case "${cmd}" in
  bwdev) buildworld_dev ;;
  bk) buildkernel_parallel ;;
  bkdev) buildkernel_dev_single ;;
  dirdeps) dirdeps_build ;;
  ci) _ci "$@" ;;
  *)
      echo "ERROR: unrecognized command '${cmd}'" >&2
      _usage
esac
