#!/bin/sh
set -ex

TARGET_HOSTNAME="$2"

case "$TARGET_HOSTNAME" in
  beastie)
    PKGLIST="pkglist-builder.txt"
    ;;
  cl100*|wyse*)
    PKGLIST="pkglist-empt.txt"
    ;;
  *)
    echo "unsupported target host: '$TARGET_HOSTNAME'" >&2
    echo "usage: $0 <command> <hostname>" >&2
    exit 1
esac

# NOTE set either of these to GENERIC for recovery or hardware testing
BUILDER_KERNCONF="MY$(hostname | tr '[:lower:]' '[:upper:]')"
TARGET_KERNCONF="MY$(echo "$TARGET_HOSTNAME" | tr '[:lower:]' '[:upper:]')"

FREEBSD_VERSION=14
BUILDER_JAIL="poudriere_stable${FREEBSD_VERSION}_${BUILDER_KERNCONF}"
TARGET_PKGBASE_JAIL="poudriere_stable${FREEBSD_VERSION}_${TARGET_KERNCONF}"

PKGBASE_REPO="/usr/local/poudriere/data/images/${TARGET_PKGBASE_JAIL}-repo/FreeBSD:${FREEBSD_VERSION}:$(uname -p)/latest"
PKGBASE_REPO_NAME=PoudrierePkgbase

PORTS_REPO="/usr/local/poudriere/data/packages/${BUILDER_JAIL}-default-${TARGET_HOSTNAME}"
PORTS_REPO_NAME=PoudrierePorts

OPTIONS_DIR="${BUILDER_JAIL}-default-${TARGET_HOSTNAME}-options"
BACKUP_DIR="hosts/${TARGET_HOSTNAME}/${OPTIONS_DIR}"

refresh_kernconf() {
    grep '^[a-z]' hosts/"${TARGET_HOSTNAME}"/"${TARGET_KERNCONF}_LINT" \
    	| sort -u \
    	| tee \
            hosts/"${TARGET_HOSTNAME}"/"${TARGET_KERNCONF}" \
            /usr/src/sys/"$(uname -p)"/conf/"${TARGET_KERNCONF}" \
            > /dev/null
}

# TODO find a cleaner way to do this
# Instructions from https://wiki.freebsd.org/PkgBase
post_pkgbase_upgrade() {
    if test -r /etc/master.passwd.pkgsave || test -r /etc/group.pkgsave ; then
        cp /etc/master.passwd.pkgsave /etc/master.passwd || true
        cp /etc/group.pkgsave /etc/group || true
        pwd_mkdb -p /etc/master.passwd
    fi
    cp /etc/sysctl.conf.pkgsave /etc/sysctl.conf || true
    find / -name '*.pkgsave' -delete
    rm -f /boot/kernel/linker.hints
}

bootstrap_builder() {
    # NOTES:
    # Must run with the following conditions:
    # * as root (with doas is fine)
    # * on a freshly-installed FreeBSD 14.0-RELEASE system
    # * inside the git repo
    #
    # REQUIRED PKGS BEFORE BOOTSTRAP:
    # * doas (configured with 'permit nopass :wheel')

    BUILDER_HOSTNAME=poudriere.home.arpa

    # NOTE use this to determine a system's CPUTYPE, then add it to a make.conf
    # inside the hosts/ directory
    #CPUTYPE=$(cc -v -x c -E -march=native /dev/null 2>&1 | sed -n 's/.*-target-cpu *\([^ ]*\).*/\1/p')

    # 1) install required packages from upstream mirror
    pkg install -y git poudriere ccache

    # 2) setup poudriere
    # TODO change ccache directory to a better global location, possibly /var/cache/ccache
    # NOTE add back if needed to the sed command:
    #   -e 's/.*TMPFS_BLACKLIST=.*/TMPFS_BLACKLIST="ghc* llvm* rust*"/' \
    #   -e 's%.*TMPFS_BLACKLIST_TMPDIR=.*%TMPFS_BLACKLIST_TMPDIR="${BASEFS}/data/cache/tmp"%' \
    sed \
    	-e "s/.*BUILDER_HOSTNAME=.*/BUILDER_HOSTNAME=${BUILDER_HOSTNAME}/" \
    	-e 's/.*ALLOW_MAKE_JOBS_PACKAGES=.*/ALLOW_MAKE_JOBS_PACKAGES="pkg ccache rust* llvm* gcc* python* cmake*"/' \
    	-e 's/.*BAD_PKGNAME_DEPS_ARE_FATAL=.*/BAD_PKGNAME_DEPS_ARE_FATAL=yes/' \
    	-e 's%.*CCACHE_DIR=.*%CCACHE_DIR=/root/.ccache%' \
    	-e 's/.*NOLINUX=.*/NOLINUX=yes/' \
    	-e 's/.*WRKDIR_ARCHIVE_FORMAT=.*/WRKDIR_ARCHIVE_FORMAT=tzst/' \
    	-e 's/.*ZPOOL=.*/ZPOOL=zroot/' \
    	/usr/local/etc/poudriere.conf.sample > /usr/local/etc/poudriere.conf

    cp "hosts/${BUILDER_HOSTNAME}/${BUILDER_HOSTNAME}"-*.conf /usr/local/etc/poudriere.d/

    sysrc kld_list+=filemon
    kldload -n filemon

    # 3) build system pkgbase

    if test ! -d /usr/src/.git; then
        git clone --depth 1 --branch "stable/${FREEBSD_VERSION}" https://git.freebsd.org/src.git /usr/src
    fi
    git -C /usr/src pull
    refresh_kernconf
    poudriere jail -c -j "$BUILDER_JAIL" -b -m src=/usr/src -B -K "$BUILDER_KERNCONF" -z "$BUILDER_HOSTNAME"

    # 4) convert system into a pkgbase installation
    mkdir -p /usr/local/etc/pkg/repos

    # TODO handle signatures
    cat > /usr/local/etc/pkg/repos/poudriere_pkgbase.conf <<EOF
${PKGBASE_REPO_NAME}: {
  url: "file://${PKGBASE_REPO}"
  enabled: yes
}
EOF

    pkg install -y -r "$PKGBASE_REPO_NAME" -g 'FreeBSD-*'
    post_pkgbase_upgrade

    if test ! -d /usr/ports/.git; then
        # 5) setup ports collection
        git clone --depth 1 https://git.freebsd.org/ports.git /usr/ports

        # 6) create poudriere ports pointer to the local ports collection
        poudriere ports -c -m null -M /usr/ports
    fi

    mkdir -p /usr/ports/distfiles
    git -C /usr/ports pull

    cp -R "$BACKUP_DIR" "$OPTIONS_DIR"
    poudriere bulk -j "$BUILDER_JAIL" -f pkglist-builder.txt -z "$BUILDER_HOSTNAME"

    # 7) reinstall all system pkgs with the new poudriere repo
    cat <<EOF > /usr/local/etc/pkg/repos/poudriere_ports.conf
${PORTS_REPO_NAME}: {
  url: "file://$PORTS_REPO"
  enabled: yes
}
EOF

    cat <<EOF > /usr/local/etc/pkg/repos/FreeBSD.conf
FreeBSD: {
  url: "pkg+https://pkg.freebsd.org/$${ABI}/latest",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: "no"
}
EOF
    pkg upgrade -y
}

COMMAND="$1"
case "$COMMAND" in
  bootstrap)
    bootstrap_builder
    ;;
  create)
    poudriere jail -c -j "${TARGET_PKGBASE_JAIL}" -b -m src=/usr/src -B -K "${TARGET_KERNCONF}" -z "${TARGET_HOSTNAME}"
    ;;
  bulk|options)
    cp hosts/"$TARGET_HOSTNAME"/"$TARGET_HOSTNAME"-common-make.conf /usr/local/etc/poudriere.d/"$TARGET_HOSTNAME"-make.conf
    cp hosts/"$TARGET_HOSTNAME"/"$TARGET_HOSTNAME"-portoptions-make.conf /usr/local/etc/poudriere.d/"$BUILDER_JAIL"-default-"$TARGET_HOSTNAME"-make.conf
    doas poudriere "$COMMAND" -j "$BUILDER_JAIL" -f "$PKGLIST" -z "$TARGET_HOSTNAME"
    ;;
  backup)
    rm -rf "$BACKUP_DIR"
    cp -R /usr/local/etc/poudriere.d/"$OPTIONS_DIR" "$BACKUP_DIR"
    cp /usr/local/etc/poudriere.d/"${TARGET_HOSTNAME}"-*.conf hosts/"$TARGET_HOSTNAME"/
    ;;
  delete)
    poudriere jail -d -j "${TARGET_PKGBASE_JAIL}" -C all -y || true
    rm -f /usr/local/etc/poudriere.d/*"${TARGET_HOSTNAME}"*.conf
    rm -rf /usr/local/poudriere/data/images/"${TARGET_PKGBASE_JAIL}"-repo
    rm -f "tarballs/${TARGET_HOSTNAME}-${PKGBASE_REPO_NAME}.tar.zst"
    ;;
  tarballs)
    mkdir -p tarballs
    tar --zstd --strip-components 9 -cvHf "tarballs/${TARGET_HOSTNAME}-${PKGBASE_REPO_NAME}.tar.zst" "$PKGBASE_REPO"
    tar --zstd --strip-components 7 -cvf "tarballs/${TARGET_HOSTNAME}-${PORTS_REPO_NAME}.tar.zst" "$PORTS_REPO"
    ;;
  kernconf)
    refresh_kernconf
    ;;
  upgrade_pkgbase)
    refresh_kernconf
    git -C /usr/src pull upstream "stable/${FREEBSD_VERSION}" --rebase --autostash
    poudriere jail -u -j "${TARGET_PKGBASE_JAIL}" -b -z "${TARGET_HOSTNAME}"
    pkg upgrade -y
    post_pkgbase_upgrade
    ;;
  upgrade_ports)
    git -C /usr/ports pull upstream main --rebase --autostash
    poudriere options -j "${BUILDER_JAIL}" -f "$PKGLIST" -z "${TARGET_HOSTNAME}"
    poudriere bulk -j "${BUILDER_JAIL}" -f "$PKGLIST" -z "${TARGET_HOSTNAME}"
    pkg upgrade -y
    ;;
  *)
    echo "unsupported command: '$COMMAND'" >&2
    exit 1
esac
