#!/bin/sh

# PROVIDE: empt
# REQUIRE: FILESYSTEMS
# BEFORE: NETWORKING

. /etc/rc.subr

name=empt
rcvar="${name}_enable"

#required_files="/etc/${name}.conf /usr/share/misc/${name}.rules"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

empt_start() {
  zpool import empt
}

empt_stop() {
  echo bye-bye
}

load_rc_config $name
run_rc_command "$1"
